teleop_twist_joy:
  ros__parameters:
    axis_linear:
      x: 1   # stick izq vertical → adelante/atrás
      y: 0   # stick izq horizontal → izquierda/derecha
      z: 4   # stick der vertical → subir/bajar
    scale_linear:
      x: 1.0
      y: 1.0
      z: 1.0

    axis_angular:
      yaw: 3   # stick der horizontal → girar
    scale_angular:
      yaw: 1.0

    enable_button: 4   # L1 debe estar presionado para mandar comandos
    enable_turbo_button: 5  # R1 para "turbo" (opcional)
